name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  NODE_OPTIONS: --max_old_space_size=4096
  FORCE_COLOR: true

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'  # Changed from 'yarn' to 'npm'
      
      # Fallback to npm if yarn.lock is not present
      - name: Check for yarn.lock
        id: check_yarn
        run: |
          if [ -f "yarn.lock" ]; then
            echo "package_manager=yarn" >> $GITHUB_OUTPUT
          else
            echo "package_manager=npm" >> $GITHUB_OUTPUT
          fi
      
      - name: Install Dependencies
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi
        
      - name: Lint
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn lint
          else
            npm run lint
          fi
        
      - name: Type Check
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn type-check
          else
            npm run type-check
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Changed from 'yarn' to 'npm'
      
      - name: Check for yarn.lock
        id: check_yarn
        run: |
          if [ -f "yarn.lock" ]; then
            echo "package_manager=yarn" >> $GITHUB_OUTPUT
          else
            echo "package_manager=npm" >> $GITHUB_OUTPUT
          fi
      
      - name: Install Dependencies
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi
      
      - name: Run Tests
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn test --coverage
          else
            npm test -- --coverage
          fi
      
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 7

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [code-quality, test]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'  # Changed from 'yarn' to 'npm'
      
      - name: Check for yarn.lock
        id: check_yarn
        run: |
          if [ -f "yarn.lock" ]; then
            echo "package_manager=yarn" >> $GITHUB_OUTPUT
          else
            echo "package_manager=npm" >> $GITHUB_OUTPUT
          fi
      
      - name: Install Dependencies
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi
      
      - name: Build
        run: |
          if [ "${{ steps.check_yarn.outputs.package_manager }}" = "yarn" ]; then
            yarn build
          else
            npm run build
          fi
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 7
